Make withExceptionHandling useful by returning the result
ColdBox/coldbox-platform pull request #437
Opened 2020-01-31 18:49 UTC by elpete

2020-02-12 23:25 UTC, jclausen commented
@elpete On adobe engines, you're going to need to use `cfconfig` to set the `errorStatusCode` to `true` in order for your tests to pass.  Out of the box, ACF returns a 200 on errors - don't ask me why.

2020-02-12 23:28 UTC, bdw429s commented
> Out of the box, ACF returns a 200 on errors - don't ask me why.

it's a security "feature" meant to prevent hackers from finding out via a script if they've caused an error on your site.  That said, I hate it because it's dumb and HTTP status codes should always represent what happened in the request.  I have seen security scanners give "false positives" just because they were able to get a 500 status code back.

2020-03-07 00:09 UTC, lmajano commented on system/testing/BaseTestCase.cfc
> +    /**
@elpete can you remove this, since we talked about leveraging the exception bean approach.

2021-03-10 16:59 UTC, lmajano requested changes

2021-03-10 16:59 UTC, lmajano commented on system/testing/BaseTestCase.cfc
> +    /**
@elpete I want to merge this, but can you provide some cleanup please.

2021-03-10 17:42 UTC, elpete commented
I don't remember what I was trying to do here.  We're probably better starting from scratch. :sweat_smile:

2021-03-10 17:42 UTC, closed without merging